setMethod("show", "design_in",
          function(object){
            cat("Total number of iterations:",object@n_sim,"\n")
            cat("Total number of simulated genes:",object@n_gene,"\n")
            cat("Total cell type number:",object@ncell_type,"\n")
            cat("Simulation scenarios:", "\n")
            print(object@scenarios)
            cat("Total number of gene expressoin strata:",object@n_strata,"\n","\n")
            cat("Mean of genetic distribution mean for each cell:","\n")
            print(object@health_lmean_m)
            cat("Var/cov of genetic distribution mean among cell types","\n")
            print(object@health_lmean_d)
            cat("\n")
            cat("Mean of genetic distribution dispersion for each cell","\n")
            print(object@lod_m)
            cat("Var/cov of genetic distribution dispersion among cell types","\n")
            print(object@lod_d)
            cat("\n")
            cat("Control group proportion simulation parameter","\n")
            print(object@health_alpha)
            cat("Case group proportion simulation parameter","\n")
            print(object@case_alpha)

          }
)

setMethod("show","cypress_out",
          function(object){
            cat("Cell type specific target TDR:","\n")
            print(object@ct_TDR_bio_smry)
            cat("Target TDR:","\n")
            print(object@TDR_bio_smry)
            cat("\n")
            cat("Cell type specific target power:","\n")
            print(object@ct_PWR_bio_smry)
            cat("Target power:","\n")
            print(object@PWR_bio_smry)
            cat("Target power by gene expression stratification:","\n")
            print(object@PWR_strata_bio_smry)
            cat("Cell type specific target power by gene expression stratification:","\n")
            print(object@PWR_strata_ct_bio_smry)
            cat("\n")
            cat("Cell type specific target FDC:","\n")
            print(object@ct_FDC_bio_smry)
            cat("Target FDC:","\n")
            print(object@FDC_bio_smry)
          }
)

setMethod(  f = "show",  signature = "est_out",
            definition = function(object) {
              cat("CYPRESS Estimated Object\n")
              cat("-------------------------------\n")
              cat("Health Alpha: ", "\n")
              print(object@health_alpha)
              cat("\n")
              cat("Case Alpha: ", "\n")
              print(object@case_alpha)
              cat("\n")
              cat("Health LMean M: ",  "\n")
              print(object@health_lmean_m)
              cat("\n")
              cat("LOD M: ", "\n")
              print(object@lod_m)
              cat("\n")
              cat("Health LMean D: ",  "\n")
              print(head(object@health_lmean_d))
              cat("...","\n")
              cat("LOD D: ", "\n")
              print(head(object@lod_d))
              cat("...","\n")
              cat("Sample CT Prop: ",  "\n")
              print(head(object@sample_CT_prop))
              cat("...","\n")
              cat("Gene Name: ",  "\n")
              print(head(object@genename))
              cat("...","\n")
              cat("Sample Name: ",  "\n")
              print(head(object@samplename))
              cat("...","\n")
              cat("CT Name: ", object@CTname, "\n")
              cat("\n")
              cat("Dimensions Z_Hat Ary: ",  "\n")
              cat("   G: ", object@dimensions_Z_hat_ary[1], "\n")
              cat("   N: ", object@dimensions_Z_hat_ary[2], "\n")
              cat("   K: ", object@dimensions_Z_hat_ary[3], "\n")
            }
)
