
setMethod("show", "cypress_out",
          function(object){
            cat("Cell type specific target TDR:", "\n")
            print(head(slot(object, "ct_TDR_bio_smry") ,4) )
#            cat("Target TDR:", "\n")
#            print(slot(object, "TDR_bio_smry"))
            cat("\n")
            cat("Cell type specific target power:", "\n")
            print(head(slot(object, "ct_PWR_bio_smry") ,4) )
            cat("\n")
#            cat("Target power:", "\n")
#            print(slot(object, "PWR_bio_smry"))
#            cat("Target power by gene expression stratification:", "\n")
#            print(slot(object, "PWR_strata_bio_smry"))
            cat("Cell type specific target power by gene expression stratification:", "\n")
            print(head( slot(object, "PWR_strata_ct_bio_smry") ,4) )
            cat("\n")
            cat("Cell type specific target FDC:", "\n")
            print(head(slot(object, "ct_FDC_bio_smry") ,4) )
#            cat("Target FDC:", "\n")
#            print(slot(object, "FDC_bio_smry"))
          }
)

setMethod(f = "show", signature = "est_out",
          definition = function(object) {
            cat("CYPRESS Estimated Object\n")
            cat("-------------------------------\n")
            cat("Health Alpha: ", "\n")
            print(slot(object, "health_alpha"))
            cat("\n")
            cat("Case Alpha: ", "\n")
            print(slot(object, "case_alpha"))
            cat("\n")
            cat("Health LMean M: ",  "\n")
            print(slot(object, "health_lmean_m"))
            cat("\n")
            cat("LOD M: ", "\n")
            print(slot(object, "lod_m"))
            cat("\n")
            # cat("Health LMean D: ",  "\n")
            # print(head(slot(object, "health_lmean_d")))
            # cat("...", "\n")
            # cat("LOD D: ", "\n")
            # print(head(slot(object, "lod_d")))
            # cat("...", "\n")
            # cat("Sample CT Prop: ",  "\n")
            # print(head(slot(object, "sample_CT_prop")))
            # cat("...", "\n")
            # cat("Gene Name: ",  "\n")
            # print(head(slot(object, "genename")))
            # cat("...", "\n")
            # cat("Sample Name: ",  "\n")
            # print(head(slot(object, "samplename")))
            # cat("...", "\n")
            # cat("CT Name: ", slot(object, "CTname"), "\n")
            # cat("\n")
            # cat("Dimensions Z_Hat Ary: ",  "\n")
            # cat("   G: ", slot(object, "dimensions_Z_hat_ary")[1], "\n")
            # cat("   N: ", slot(object, "dimensions_Z_hat_ary")[2], "\n")
            # cat("   K: ", slot(object, "dimensions_Z_hat_ary")[3], "\n")
          }
)
